import "./animations.scss";
import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ScrollUp from "@/components/scroll-up";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Exim Global",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <ScrollUp />
      </body>
    </html>
  );
}
